name = "prapatti-guestbook"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "prapatti-guestbook"
database_id = "9e8d9706-3b97-4344-9a88-c4ae9205c412"
